---
title: "Axial Seamount 16S"
format:
  html:
    toc: true
    toc-depth: 2
editor: visual
---

# Axial Seamount 16S rRNA gene sequencing

From 2023 expedition


## Sequence analysis

Running QIIME2 here: `/scratch/group/hu-lab/qiime-axial-2023_18S_16S`


SLURM script for running 16S analysis:
```{r}
#| eval: false
# Load qiime2
module load QIIME2/2024.10-Amplicon

echo "import sequences"

qiime tools import \
 --type 'SampleData[PairedEndSequencesWithQuality]' \
 --input-path /scratch/group/hu-lab/qiime-axial-2023_18S_16S/manifest-axial-prok \
 --output-path /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/pe-input-16s.qza \
 --input-format PairedEndFastqManifestPhred33V2

qiime demux summarize \
        --i-data /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/pe-input-16s.qza \
        --o-visualization /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/pe-input-16s.qzv

echo "Use cutadapt to remove primer sequences"

qiime cutadapt trim-paired \
        --i-demultiplexed-sequences /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/pe-input-16s.qza \
        --p-cores $SLURM_CPUS_PER_TASK \
        --p-front-f GTGYCAGCMGCCGCGGTAA \
        --p-front-r GGACTACNVGGGTWTCTAAT \
        --p-cores $SLURM_CPUS_PER_TASK \
        --p-front-f GTGYCAGCMGCCGCGGTAA \
        --p-front-r GGACTACNVGGGTWTCTAAT \
        --p-error-rate 0.1 \
        --p-overlap 3 \
        --p-match-adapter-wildcards \
        --o-trimmed-sequences /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/pe-input-trimmed-16s.qza

qiime demux summarize \
        --i-data /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/pe-input-trimmed-16s.qza \
        --o-visualization /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/pe-input-trimmed-16s.qzv

qiime dada2 denoise-paired \
        --i-demultiplexed-seqs /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/pe-input-trimmed-16s.qza \
        --p-trunc-len-f 250 \
        --p-trunc-len-r 225 \
        --p-max-ee-f 2 \
        --p-max-ee-r 2 \
        --p-min-overlap 10 \
        --p-pooling-method independent \
        --p-n-reads-learn 1000000 \
        --p-n-threads $SLURM_CPUS_PER_TASK \
        --p-chimera-method pooled \
        --o-table /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/pe-trimmed-asv-table-16s.qza \
        --o-representative-sequences /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/pe-trimmed-asv-ref-seq-16s.qza \
        --o-denoising-stats /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/pe-trimmed-asv-dada2stats-16s.qza

echo "dada2 step completed"

qiime tools export \
        --input-path /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/pe-trimmed-asv-table-16s.qza \
        --output-path /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/

biom convert \
        -i /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/feature-table.biom \
        -o /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/axial-2023-16s-asv-table.tsv \
        --to-tsv

echo "asv table is prepped"

qiime metadata tabulate \
        --m-input-file /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/pe-trimmed-asv-dada2stats-16s.qza \
        --o-visualization /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/pe-trimmed-asv-dada2stats-16s.qzv


echo "assign taxonomy"

qiime feature-classifier classify-consensus-vsearch \
        --i-query /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/pe-trimmed-asv-ref-seq-16s.qza \
        --i-reference-reads /scratch/group/hu-lab/databases/silva/silva-138-99-seqs.qza \
        --i-reference-taxonomy /scratch/group/hu-lab/databases/silva/silva-138-99-tax.qza \
        --output-dir /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/taxonomy-0.9_0.8_SILVA \
        --p-threads $SLURM_CPUS_PER_TASK \
        --p-maxaccepts 10 \
        --p-perc-identity 0.90 \
        --p-min-consensus 0.80
        
        qiime tools export \
        --input-path /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/taxonomy-0.9_0.8_SILVA/search_results.qza \
        --output-path /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/taxonomy-0.9_0.8_SILVA/tax-result-SILVA-16s

qiime tools export \
        --input-path /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/taxonomy-0.9_0.8_SILVA/classification.qza \
        --output-path /scratch/group/hu-lab/qiime-axial-2023_18S_16S/16S_output_axial_2023/taxonomy-0.9_0.8_SILVA/
```

## Set up R environment & import data

```{r}
library(tidyverse)
library(plotly)
library(readxl)
```

```{r}
asv <- read.delim(file = "input-data/axial-2023-16s-asv-table.tsv", sep = "\t", skip = 1)
# head(asv)
# colnames(asv)
```

```{r}
tax <- read.delim(file = "input-data/taxonomy-16S.tsv", sep = "\t")
head(tax)
```

```{r}
metadata_samples <- read_excel("metadata-axial-2023.xlsx", sheet = "metadata") %>% 
  select(-NUM, -OLD_NAME_ARCHIVE)
biotic <- read_excel("metadata-axial-2023.xlsx", sheet = "biotic")
# head(metadata_samples)
# head(biotic)
```

### Merge data

```{r}
asv_long_tax <- asv %>% 
  pivot_longer(cols = -c("X.OTU.ID"), names_to = "SAMPLE_NAME", values_to = "SEQUENCE_COUNT") %>% 
  select(Feature.ID = "X.OTU.ID", SAMPLE_NAME, SEQUENCE_COUNT) %>% 
  filter(grepl("AXIAL_23", SAMPLE_NAME)) %>% 
  filter(SEQUENCE_COUNT > 0) %>% 
  left_join(metadata_samples) %>% 
  left_join(tax)

head(asv_long_tax)
# unique(asv_long_tax$collection_method)
colnames(asv_long_tax)
```

# Revise dataframe for plotting

```{r}
unique(asv_long_tax$sample_name)
```


```{r}
refined_asv_table <- asv_long_tax %>% 
  # Removed controls
  filter(sample_name != "ControlTreatment") %>% 
  # Removed ASVs with only 1 sequence
  filter(SEQUENCE_COUNT > 1) %>% 
  group_by(SAMPLE_NAME, dive_ctd, sample_name, collection_method, sample_identifier, filter, processing, location_name, Taxon) %>% 
  summarise(AVG_SEQ = mean(SEQUENCE_COUNT)) %>% 
  separate(Taxon, into = c("Domain", "Phylum", "Class", "Order", "Family", "Genus-Spp"), sep = "; ", remove = FALSE)
  

head(refined_asv_table)  
unique(refined_asv_table$filter)
unique(refined_asv_table$Domain)
```


## Phylum level

```{r, fig.height=18, fig.width=11}
bar_plot_Phylum <- refined_asv_table %>% 
  filter(Domain != "Unassigned") %>% 
  filter(Domain != "d__Eukaryota") %>% 
  group_by(collection_method, location_name, Domain, Phylum) %>% 
  summarise(SEQ_SUM = sum(AVG_SEQ)) %>% 
  ggplot(aes(x = location_name, y = SEQ_SUM, fill = Phylum)) +
  geom_bar(stat = "identity", position = "fill",color = "black", width = 0.8) +
  theme_classic() +
  theme(legend.position = "bottom") +
  labs(x = "Diffuse vent fluid", y = "Sequence relative abundance",
       title = "Phylum level")

ggplotly(bar_plot_Phylum)
```

### Non-interactive plot

```{r, fig.height=18, fig.width=11}
bar_plot_Phylum
```


## Phylum-class subset
Isolate: a subset of bacteria
```{r}
subset <- c("p__Proteobacteria","p__Campilobacterota", "p__Desulfobacterota", "p__Bacteroidota")
```

```{r}
# View(refined_asv_table %>% 
#   filter(Domain != "Unassigned") %>% 
#   filter(Domain != "d__Eukaryota"))
```


```{r, fig.height=18, fig.width=18}
bar_plot_subset_bacteria <- refined_asv_table %>% 
  filter(Domain != "Unassigned") %>% 
  filter(Domain != "d__Eukaryota") %>% 
  filter(Phylum %in% subset) %>% 
  unite(tax, Phylum, Class, Order, sep = "; ") %>% 
  group_by(location_name, tax) %>% 
  summarise(SEQ_SUM = sum(AVG_SEQ)) %>% 
  ggplot(aes(x = location_name, y = SEQ_SUM, fill = tax)) +
  geom_bar(stat = "identity", position = "fill",color = "black", width = 0.8) +
  theme_classic() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1)) +
  labs(x = "Diffuse vent fluid", y = "Sequence relative abundance",
       title = "Phylum-Class level")

ggplotly(bar_plot_subset_bacteria)
```
### non-interactive

```{r, fig.height=16, fig.width=14}
bar_plot_subset_bacteria
## Report all taxa represented
```

```{r}
tmp <- refined_asv_table %>% ungroup() %>% 
  select(Taxon) %>% distinct()

```

