project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - axial-seamount-amplicon-analysis-2023.qmd
    - 16S-AxialSeamount2023.qmd

execute:
  eval: true

website:
  title: "Axial Seamount 2023"
  navbar:
    left:
      - href: axial-seamount-amplicon-analysis-2023.qmd
        text: 18S rRNA results
      - href: 16S-AxialSeamount2023.qmd
        text: 16S rRNA results

format:
  html:
    theme:
      - slate
    toc: true
    toc-location: left
    number-sections: true
    number-depth: 3



